#!/bin/bash

# variables
theme="$HOME/.config/rofi/scripts/screenshot/style.rasi"
save_dir="$HOME/Pictures/screenshots"
filename="capture-$(date +%Y-%m-%d-%s).png"

if [ "$1" = "--clipboard-only" ]; then
  command="grimblast -w 0.5 -n copy"
  fullpath=""
else
  command="grimblast -w 0.5 -n save"
  fullpath="$save_dir/$filename"
fi

# options to be displayed
region="󰆞"
output=""
window=""
# folder=""

selected="$(echo -e "$region\n$output\n$window\n" | rofi -dmenu -theme "${theme}" -kb-row-left "h" -kb-row-right "l")"

case $selected in
$region)
  $command area "$fullpath"
  ;;
$output)
  $command screen "$fullpath"
  ;;
$window)
  $command active "$fullpath"
  ;;
# $folder)
#   ~/.config/rofi/scripts/screenshot/screenshot_selection
#   ;;
esac
