#!/bin/bash

# variables
theme="$HOME/.config/rofi/scripts/screenshot/style.rasi"
save_dir="$HOME/Pictures/screenshots"
filename="capture-$(date +%Y-%m-%d-%s).png"

if [ "$1" = "--clipboard-only" ]; then
  command="hyprshot --clipboard-only"
else
  command="hyprshot -o $save_dir -f $filename $extra_args"
fi

# options to be displayed
region="󰆞"
output=""
window=""
folder=""

selected="$(echo -e "$region\n$output\n$window\n" | rofi -dmenu -theme "${theme}" -kb-row-left "h" -kb-row-right "l")"
case $selected in
$region)
  $command -m region
  ;;
$output)
  $command -m output
  ;;
$window)
  $command -m window
  ;;
# $folder)
#   ~/.config/rofi/scripts/screenshot/screenshot_selection
#   ;;
esac
