session_name: home
windows:
  - window_name: term
    shell_command_before: 
      - cd ~/ # first command 
    layout: 1774,185x42,0,0{102x42,0,0,1,82x42,103,0[82x21,103,0,2,82x20,103,22,3]}
    panes:
      - neomutt # pane no. 1
      - archlinuxinfo
  # pane no. 2
      - peaclock # pane no. 3

  - window_name: svu 
    shell_command_before: 
      - ssh -X mindhunter@svu
