session_name: home
windows:
  - window_name: term
    shell_command_before: 
      - cd ~/ # first command 
    panes:
      - ~/.bin/tmuxp_banner

  - window_name: svu 
    shell_command_before: 
      - ssh mindhunter@svu
